title: BurmillaOS
description: BurmillaOS documentation
<<<<<<< HEAD
theme: jekyll-theme-tactile
=======
remote_theme: tomjoht/documentation-theme-jekyll
>>>>>>> 2f1c93b (use tomjoht/documentation-theme-jekyll as theme)
