baseurl = "https://burmillaos.org/"
languageCode = "en-us"
title = "BurmillaOS"

theme = "book"
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']
pygmentsStyle = "monokai"

[Params]
  BookTheme = 'auto'
  BookToC = true
  favicon = "img/favicon.ico"
  BookDateFormat = "January 2, 2006"
  BookSearch = true
  BookComments = false
  BookRepo = 'https://github.com/burmilla/burmilla.github.io'
  BookPortableLinks = true
  BookServiceWorker = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
